### ISSUE TITLE
Improper damage calculation

### ISSUE THREAD

**Issue by Choosy9353** [ForwardFeed/Redux-Elite-Calc#6]
Player damage calculation appears to be inconsistent with game damage calculation. Unsure of cause.

**Comment by ForwardFeed** [comment]
Yes it happens, sometimes because i misimplemented something or because the pipeline of data from the game file to the calc which is based of regex parsing is prone to mistakes.
Since the game is updated often and my system of changing version is lazily implemented people can have the wrong version. Which is something i should be more consistent about.

In case of a wrong calculation (it will happens).
There is a download report, or you can send a screen of a wrong calculation.
Later i'll add the share calculation feature which will be better for that as it will only be a link to share.
